pythonix4/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login

from django.views.generic.base import TemplateView

from pythonix4.router_api_v1 import router

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api_v1/', include(router.urls, namespace='api_v1')),
    url(r'^$', TemplateView.as_view(template_name="app_client/login.html"), name='index'),
    url(r'^pythonix_admin/', include('pythonix_admin.urls', app_name='pythonix_admin', namespace='pythonix_admin')),
    url(r'^pythonix_client/', include('pythonix_client.urls', app_name='pythonix_client', namespace='pythonix_client')),
    url(r'^logout/$', login, {'template_name': 'app_client/login.html'}, name='logout')
]

pythonix_client/urls.py
from django.conf.urls import url

from pythonix_client import views


urlpatterns = [
    url(r'^$', views.ClientIndexPage.as_view(), name='client_index'),
    url(r'^client_login/$', views.client_login, name='client_login'),
    url(r'^my_login/$', views.my_login, name='my_login'),
    url(r'^close_order/$', views.close_order, name='close_order'),
]

templates/app_client/login.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Pythonix | Log in</title>
  {% load staticfiles %}
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css" %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static "dist/css/AdminLTE.min.css" %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static "plugins/iCheck/square/blue.css" %}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="../../index2.html"><b>Pythonix</b>Billing</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Войти в личный кабинет</p>

    <form action="{% url 'pythonix_client:client_login' %}" method="post">
        {% csrf_token %}
      <div class="form-group has-feedback">
        <input type="text" class="form-control" placeholder="Login" name="login">
        <span class="glyphicon glyphicon-user form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input type="password" class="form-control" placeholder="Password" name="password">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-8">
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">Войти</button>
        </div>
        <!-- /.col -->
      </div>
    </form>

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 2.2.3 -->
<script src="../../plugins/jQuery/jquery-2.2.3.min.js"></script>
<!-- Bootstrap 3.3.6 -->
<script src="../../bootstrap/js/bootstrap.min.js"></script>
<!-- iCheck -->
<script src="../../plugins/iCheck/icheck.min.js"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' // optional
    });
  });
</script>
</body>
</html>