pythonix4/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login

from django.views.generic.base import TemplateView

from pythonix4.router_api_v1 import router

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api_v1/', include(router.urls, namespace='api_v1')),
    url(r'^$', TemplateView.as_view(template_name="app_client/login.html"), name='index'),
    url(r'^pythonix_admin/', include('pythonix_admin.urls', app_name='pythonix_admin', namespace='pythonix_admin')),
    url(r'^pythonix_client/', include('pythonix_client.urls', app_name='pythonix_client', namespace='pythonix_client')),
    url(r'^logout/$', login, {'template_name': 'app_client/login.html'}, name='logout')
]

pythonix_admin/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from pythonix_admin import views
from django.contrib.auth.decorators import login_required


urlpatterns = [
    url(r'^$', views.AdminIndexPage.as_view(), name='admin_index'),
    url(r'^create_client/$', views.CreateClient.as_view(), name='create_client'),
    url(r'^get_free_ipaddress/(\d{1,9})/$', login_required(views.get_free_ipaddress, login_url='/admin/'), name='get_free_ipaddress'),
    url(r'^abbreviation_physical_network/(\d{1,9})/$', views.abbreviation_physical_network, name='abbreviation_physical_network'),
    url(r'^get_streets/(\d{1,9})/$', login_required(views.get_streets, login_url='/admin/'), name='get_streets'),
    url(r'^client_list/(?P<pk>\d+)/$', login_required(views.ClientsList.as_view(), login_url='/admin/'), name='client_list'),
    url(r'^client_info/(?P<pk>\d+)/$', views.ClientInfoView.as_view(), name='client_info'),
    url(r'^del_client/(?P<pk>\d+)/$', views.ClientDelete.as_view(), name='del_client'),
    url(r'^pay_balance/(\d{1,9})/(\d{1,9})/(\d{1,9})/$', views.pay_balance, name='pay_balance'),
    url(r'^client_on_off/(\d{1,9})/(\d{1,9})/$', views.client_on_off, name='client_on_off'),
    url(r'^get_status_client/(\d{1,9})/$', views.getStatusClient, name='get_status_client'),
    url(r'^get_pon_info_client/(\d{1,9})/$', views.get_pon_info_client, name='get_pon_info_client'),
    #url(r'^migrates/$', views.migrates, name='migrates'),
    url(r'^get_client_groups/(\d{1,9})/$', views.get_client_groups, name='get_client_groups'),
    url(r'^client_connection_list/(?P<pk>\d+)/$', login_required(views.ClientsConnectionList.as_view(), login_url='/admin/'),name='client_connection_list'),
    url(r'^update_password/(\d{1,9})/$', views.update_password, name='update_password'),
    url(r'^create_order/$', views.CreateOrder.as_view(), name='create_order'),
    url(r'^order_info/(?P<pk>\d+)/$', views.OrderInfoView.as_view(), name='order_info'),
    url(r'^send_sms_info_client_ajax/(\d{1,9})/(\d{1,9})/$', views.send_sms_info_client_ajax, name='send_sms_info_client_ajax'),
    url(r'^payment_from_pay_systems/$', views.payment_from_pay_systems, name='payment_from_pay_systems'),
]

pythonix_admin/models.py
from django.conf import settings
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

import datetime
from macaddress.fields import MACAddressField

from pythonix_admin import bl
from scripts.action_mikrotik import ActionMikroTik


# Сотрудники
class Employee(models.Model):
    ROLE_SUPER_ADMIN = 'ROLE_SUPER_ADMIN'
    ROLE_ADMIN = 'ROLE_ADMIN'
    ROLE_OPERATOR_PAYER = 'OPERATOR_PAYER'
    ROLE_OPERATOR = 'ROLE_OPERATOR'
    ROLE_INSTALLER = 'ROLE_INSTALLER'

    ROLE_METHODS = {
        ROLE_SUPER_ADMIN: ('show', 'add', 'delete', 'pay', 'log'),
        ROLE_ADMIN: ('show', 'add', 'delete', 'pay'),
        ROLE_OPERATOR_PAYER: ('show', 'pay'),
        ROLE_OPERATOR: ('show',),
        ROLE_INSTALLER: ('',)
    }

    ROLE_CHOICES = (
        (ROLE_SUPER_ADMIN, ROLE_SUPER_ADMIN),
        (ROLE_ADMIN, ROLE_ADMIN),
        (ROLE_OPERATOR_PAYER, ROLE_OPERATOR_PAYER),
        (ROLE_OPERATOR, ROLE_OPERATOR),
        (ROLE_INSTALLER, ROLE_INSTALLER),
    )

    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                related_name='profile_employee')
    permissions_role = models.CharField(max_length=255, verbose_name='Выбор привелегий доступа',
                                        default=ROLE_OPERATOR, choices=ROLE_CHOICES)
    mobile_phone = models.CharField(max_length=13, validators=[bl.validate_phone], verbose_name='Номер телефона')


    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'

    def __str__(self):
        return '{} {}'.format(self.user.first_name, self.user.last_name)


# Физическая сеть
class PhysicalNetwork(models.Model):
    name = models.CharField(max_length=150, verbose_name='Название физической сети')
    select_admin = models.ManyToManyField(Employee, verbose_name='Выбор администратора', related_name='admins')
    abbreviation = models.CharField(max_length=150, verbose_name='Аббревиатура физической сети')
    channel_width = models.IntegerField(verbose_name='Ширина канала', blank=True, null=True)

    class Meta:
        verbose_name = 'Физическая сеть'
        verbose_name_plural = 'Физические сети'
        db_table = 'physical_network'

    def __str__(self):
        return '{}'.format(self.name)


# Сервера
class Servers(models.Model):
    SERVER_OS = (
        ('mikrotik', 'MikroTik RouterOS'),
    )

    title = models.CharField(max_length=150, verbose_name='Название Сервера')
    physical_network = models.ForeignKey(PhysicalNetwork, verbose_name='Выбор физической сети')
    device_type = models.CharField(max_length=255, verbose_name='Выбор операционной системы', default=1, choices=SERVER_OS)
    network_address = models.GenericIPAddressField(verbose_name='Сетевой адрес устройства')
    login = models.CharField(max_length=50, verbose_name='Логин для доступа к устройству')
    password = models.CharField(max_length=50, verbose_name='Пароль для доступа к устройству')
    api_port = models.IntegerField(verbose_name='API порт', default=8728)
    status_on_off = models.BooleanField(verbose_name='Состояние работы сервера', default=True)
    radius_used = models.BooleanField(default=False, verbose_name='Использование радиус сервера')

    class Meta:
        verbose_name = 'Сервер'
        verbose_name_plural = 'Сервера'
        db_table = 'device'

    def __str__(self):
        return '{}'.format(self.title)


# IP Подсети v4
class IPV4Networks(models.Model):
    MASK_CHOICES = tuple([(i, i) for i in range(1, 33)])
    ipv4networks = models.GenericIPAddressField(verbose_name='IP Подсети')
    CIDR = models.IntegerField(choices=MASK_CHOICES, default=24)
    ppp_auth = models.BooleanField(default=True, verbose_name='Использует PPP авторизацию')

    class Meta:
        verbose_name = "Подсеть IPv4"
        verbose_name_plural = 'Список подсетей IPv4'
        db_table = "ip_v4_networks"

    def __str__(self):
        return '{}'.format(self.ipv4networks)


# Группы клиентов
class ClientsGroups(models.Model):
    title = models.CharField(max_length=50, verbose_name='Название группы')
    ipv4networks_list = models.ManyToManyField(IPV4Networks, verbose_name='Список подсетей IPv4', related_name='networks')
    select_admin = models.ManyToManyField(Employee, verbose_name='Выбор администратора', related_name='admin_clients_groups')
    select_server = models.ManyToManyField(Servers, verbose_name='Выбор сервера', related_name='servers')

    class Meta:
        verbose_name = 'Группа клиентов'
        verbose_name_plural = 'Группы клиентов'
        db_table = 'clients_groups'

    def __str__(self):
        return '{}'.format(self.title)


# Тарифы
class Tarifs(models.Model):
    UNIT_SPEED = (
    ('k', 'k'),('M', 'M'),
    )

    select_physicalnetwork = models.ForeignKey(PhysicalNetwork, verbose_name='Выбор физической сети')
    title = models.CharField(max_length=150, verbose_name='Название тарифа')
    speed_up = models.IntegerField(verbose_name='Исходящая скорость, значение')
    speed_down = models.IntegerField(verbose_name='Входящая скорость, значение')
    speed_up_unit = models.CharField(max_length=1, verbose_name='Исходящая скорость, единица измерения', choices=UNIT_SPEED)
    speed_down_unit = models.CharField(max_length=1, verbose_name='Входящая скорость, единица измерения', choices=UNIT_SPEED)
    price = models.IntegerField(verbose_name='Абонплата')
    speed_limit = models.BooleanField(verbose_name='Лимитирование скорости', default=False)
    limit_rule = models.CharField(max_length=200, verbose_name='Правило, лимита', blank=True, null=True,)
    add_rule_in_device = models.BooleanField(verbose_name='Создавать ли правила в устройстве', default=True)
    # Период работы клиентов с первого по первое True, с дня пополнения False
    fix_work_period = models.BooleanField(default=True, verbose_name='Работает с первого по первое')


    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):

        if self.add_rule_in_device:
            try:
                for device in Servers.objects.filter(physical_network_id=self.select_physicalnetwork):
                    action_mikrotik = ActionMikroTik(device)
                    action_mikrotik.add_tarif(self.speed_up, self.speed_up_unit, self.speed_down, self.speed_down_unit)
                    return super().save(force_insert=False, force_update=False, using=None,
                            update_fields=None)
            except:
                return False
        else:
            return super().save(force_insert=False, force_update=False, using=None,
                                update_fields=None)

    class Meta:
        verbose_name = 'Тариф'
        verbose_name_plural = 'Тарифы'
        db_table = 'tarifs'

    def __str__(self):
        return '{} {}'.format(self.title, self.select_physicalnetwork.name)

# Улицы
class Streets(models.Model):
    title = models.CharField(max_length=150, verbose_name='Название улицы')
    select_physical_network = models.ForeignKey(PhysicalNetwork, verbose_name='Выбор физической сети', related_name='streets')


    class Meta:
        verbose_name = 'Улицу'
        verbose_name_plural = 'Улицы'
        db_table = 'streets'

    def __str__(self):
        return '{} {}'.format(self.title, self.select_physical_network.name)


# Клиенты
class Clients(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='client')
    ip_address = models.GenericIPAddressField(verbose_name='IP адрес клиена')
    ipv6_address = models.GenericIPAddressField(verbose_name='IPv6 адрес клиена', default="2001:0db8:11a3:09d7:1f34:8a2e:07a0:765d")
    send_sms = models.BooleanField(verbose_name='Желание получать смс', default=False)
    select_tarif = models.ForeignKey(Tarifs, verbose_name='Выбор тарифа')
    select_clients_group = models.ForeignKey(ClientsGroups, verbose_name='Выбор группы клиентов')
    create_date = models.DateField(verbose_name='Дата подключения', auto_now_add=True)
    end_used_date = models.DateField(verbose_name='Дата окончяния услуги', default=(datetime.datetime.now() + datetime.timedelta(days=settings.NEW_CLIENT_DAYS)))
    select_street = models.ForeignKey(Streets, verbose_name='Выбор улицы', blank=True, null=True)
    mobile_phone = models.CharField(max_length=50, verbose_name='Мобильный телефон', blank=True, null=True,)
    home_address = models.CharField(max_length=50, verbose_name='Домашний адрес', blank=True, null=True,)
    network_traffic_per_day = models.IntegerField(verbose_name='Сетевой трафик за день', null=True, default=0)
    network_traffic_for_the_month = models.IntegerField(verbose_name='Сетевой трафик за месяц', null=True, default=0)
    balance = models.IntegerField(verbose_name='Баланс', default=0)
    internet_status = models.BooleanField(verbose_name='Статус клиента, доступ разрешен/запрещен', default=True)
    error_card = models.IntegerField(verbose_name='Ошибки пополнения карточкой', null=True, default=0)
    deleted_user = models.BooleanField(default=False, verbose_name='Статус удаления пользователя')
    key = models.CharField(max_length=50)
    login = models.CharField(max_length=50, verbose_name='Логин', default='')
    exemption = models.BooleanField(default=False)
    # Период работы клиентов с первого по первое True, с дня пополнения False
    fix_work_period = models.BooleanField(default=False, verbose_name='Работает с первого по первое')
    vk = models.CharField(max_length=255, verbose_name='Профиль Вконтакте', default='', blank=True, null=True)
    facebook = models.CharField(max_length=255, verbose_name='Профиль в facebook', default='', blank=True, null=True)
    mac_address = MACAddressField(null=True, blank=True, integer=False, verbose_name='МАС адрес клиента')
    onu_mac_address = MACAddressField(null=True, blank=True, integer=False, verbose_name='МАС адрес ONU')

    class Meta:
        verbose_name = "Клиент"

templates/app_admin/clients_list.html
{% extends 'app_admin/base.html' %}
{% load cms %}
{% load staticfiles %}
  {% block jscss_block_top %}
      <!-- Bootstrap 3.3.6 -->
      <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css" %}">
      <!-- Font Awesome -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
      <!-- Ionicons -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
      <!-- jvectormap -->
      <link rel="stylesheet" href="{% static "plugins/jvectormap/jquery-jvectormap-1.2.2.css" %}">
      <link rel="stylesheet" href="{% static "plugins/datatables/dataTables.bootstrap.css" %}">
      <!-- Theme style -->
      <link rel="stylesheet" href="{% static "dist/css/AdminLTE.min.css" %}">
      <!-- AdminLTE Skins. Choose a skin from the css/skins
           folder instead of downloading all of them to reduce the load. -->
      <link rel="stylesheet" href="{% static "dist/css/skins/_all-skins.min.css" %}">

      <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
      <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
  {% endblock %}
{% block content %}
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Клиентов {{ clients_list.count }}
          </h1>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-xs-12">

               <!-- /.box -->

          <div class="box">
            <div class="box-header">
                <a href="{% url 'pythonix_admin:client_connection_list' client_group_id %}" class="btn btn-default">Подключенные клиенты</a>
                <a href="" class="btn btn-default">Лишние PPP</a>
                <a href="" class="btn btn-default">Лишние address list</a>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>Адрес</th>
                    <th>Баланс</th>
                    <th>Дата отключения</th>
                    <th>Тариф</th>
                    <th>IP</th>
                    <th>login</th>
                    <th>Действия</th>
                </tr>
                </thead>
                <tbody>
                    {% for client in clients_list %}
                      <tr>
                        <th>{{ client.select_street.title }} {{ client.home_address }}</th>
                        <th>{{ client.balance }}</th>
                        <th>{{ client.end_used_date }}</th>
                        <th>{{ client.select_tarif.title }}</th>
                        <th>{{ client.ip_address }}</th>
                        <th>{{ client.login }}</th>
                            {% if client.internet_status == True %}
                                <th><a href="{% url 'pythonix_admin:client_info' client.id %}"><button class="btn btn-block btn-default">Инфо</button></a></th>
                            {% else %}
                                <th><a href="{% url 'pythonix_admin:client_info' client.id %}"><button class="btn btn-block btn-danger">Инфо</button></a></th>
                            {% endif %}
                      </tr>
                    {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                   <th>Адрес</th>
                    <th>Баланс</th>
                    <th>Дата отключения</th>
                    <th>Тариф</th>
                    <th>IP</th>
                    <th>login</th>
                    <th>Действия</th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->

            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->
{% endblock %}

{% block jscss_block_bottom %}
    <!-- jQuery 2.2.3 -->
    <script src="{% static "plugins/jQuery/jquery-2.2.3.min.js" %}"></script>
    <!-- Bootstrap 3.3.6 -->
    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
    <!-- DataTables -->
    <script src="{% static "plugins/datatables/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "plugins/datatables/dataTables.bootstrap.min.js" %}"></script>
    <!-- SlimScroll -->
    <script src="{% static "plugins/slimScroll/jquery.slimscroll.min.js" %}"></script>
    <!-- FastClick -->
    <script src="{% static "plugins/fastclick/fastclick.js" %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static "dist/js/app.min.js" %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static "dist/js/demo.js" %}"></script>
    <!-- page script -->
    <script>
      $(function () {
        $("#example1").DataTable();
        $('#example2').DataTable({
          "paging": true,
          "lengthChange": false,
          "searching": false,
          "ordering": true,
          "info": true,
          "autoWidth": false
        });
      });
    </script>
{% endblock %}

templates/app_admin/create_client.html
{% extends 'app_admin/base.html' %}
{% load cms %}
{% block content %}
     <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Создание клиента
          </h1>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <!-- left column -->
            <div class="col-md-6">
              <!-- general form elements -->
              <div class="box box-default">
                <div class="box-header with-border">
                  <h3 class="box-title">Форма создания клиента</h3>
                </div><!-- /.box-header -->
                <!-- form start -->
                 <form method="POST" class="b-form" name="add_client_form" id="resume-form" enctype="multipart/form-data" action="{% url 'pythonix_admin:create_client' %}">
                     {% csrf_token %}
                  <div class="box-body">
                    <div class="form-group">
                      <label>Выбор сети</label>
                      <select class="form-control" id="physical_networks" name="name_physical_networks">
                            <option value="">Выбрать сеть</option>
                          {% for physical_network in user.profile_employee.admins.all %}
                            <option value="{{ physical_network.id }}">{{ physical_network.name }}</option>
                          {% endfor %}
                      </select>
                    </div>
                    {% lite_include 'app_admin/__includes/form_fields/select.html' field=form.select_clients_group %}

                      <!-- Список свободных ip -->
                    <div class="form-group">
                      <label>Выбор свободного IP</label>
                      <select class="form-control" id="select_ip" name="name_select_ip">
                      </select>
                    </div>
                    {% lite_include 'app_admin/__includes/form_fields/input_text.html' field=form.ip_address %}
                    {% lite_include 'app_admin/__includes/form_fields/input_text.html' field=form.ipv6_address %}
                    {% lite_include 'app_admin/__includes/form_fields/input_text.html' field=form.login %}
                    {% lite_include 'app_admin/__includes/form_fields/radio.html' field=form.send_sms %}
                    {% lite_include 'app_admin/__includes/form_fields/select.html' field=form.select_tarif %}
                    <div class="form-group">
                      <label>Выбор улицы</label>
                      <select class="form-control" id="id_select_street" name="select_street">
                      </select>
                    </div>
                    {% lite_include 'app_admin/__includes/form_fields/input_text.html' field=form.mobile_phone %}
                    {% lite_include 'app_admin/__includes/form_fields/input_text.html' field=form.home_address %}
                    {% lite_include 'app_admin/__includes/form_fields/input_text.html' field=form.balance %}
                    {% lite_include 'app_admin/__includes/form_fields/input_text.html' field=form.mac_address %}
                    {% lite_include 'app_admin/__includes/form_fields/input_text.html' field=form.onu_mac_address %}

                  </div><!-- /.box-body -->

                  <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Создать</button>
                  </div>
                </form>
              </div><!-- /.box -->



            </div><!--/.col (left) -->


          </div>   <!-- /.row -->
        </section><!-- /.content -->
{% endblock %}

{% block jscss_block_bottom %}
    {{ block.super }}
    <script type="application/javascript">

        // Выбор группы клиентов из списка
        $('#id_select_clients_group').change(function() {
            var client_group = $("select#id_select_clients_group").val();
            var page_url = '/pythonix_admin/get_free_ipaddress/' + client_group + '/';
            $.get(page_url, function(data) { //Выполняем запрос на получение списка свободных ip.

                    var text = "<option value=''>Выберите ip адрес</option>";
                    for (var i in data) {  //Наполняем список элементами.
                        add_element = "<option value="+i+">"+data[i]+"</option>";
                        text += add_element;

                    }
                    document.add_client_form.select_ip.innerHTML = text;
                });
        });

        // Выбор свободного ip адреса
        $('#select_ip').change(function() {
            var free_ip = $("select#select_ip").val();
            $('#id_ip_address').val(free_ip);
        });

        // Выбор физической сети
        $('#physical_networks').change(function() {
            var physical_network = $("select#physical_networks").val();
            var page_url = '/pythonix_admin/abbreviation_physical_network/' + physical_network + '/';
            var getStreetsUrl = '/pythonix_admin/get_streets/' + physical_network + '/'
            if (physical_network != ""){
                // Получаем абривиатуру выбранной сети
                $.get(page_url, function(data) {
                    $('#id_login').val(data['abbreviation']+'_');
                });

                $.get(getStreetsUrl, function(data) {
                    var text = "<option value=''>Выберите улицу</option>";
                    for (var i in data) {
                        add_element = "<option value="+i+">"+data[i]+"</option>";
                        text += add_element;
                    }
                    document.add_client_form.select_street.innerHTML = text;
                });

                // Список групп клиентов, выбранной сети
                var page_url = '/pythonix_admin/get_client_groups/' + physical_network + '/';
                $.get(page_url, function(data) {
                    var text = "<option value=''>Выберите группу клиентов</option>";
                    for (var i in data) {
                        add_element = "<option value="+i+">"+data[i]+"</option>";
                        text += add_element;

                    }
                    document.add_client_form.select_clients_group.innerHTML = text;
                });
            }

        });
    </script>
{% endblock %}

templates/app_admin/order_info.html
{% extends 'app_admin/base.html' %}
{% load cms %}
{% block content %}
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
              Редактирование заявки
          </h1>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <!-- left column -->
            <div class="col-md-6">
              <!-- general form elements -->
              <div class="box box-default">
                <div class="box-header with-border">
                  <h3 class="box-title">Форма обнавления информации о клиенте</h3>
                </div><!-- /.box-header -->
                <!-- form start -->
                 <form method="POST" class="b-form" name="add_client_form" id="resume-form" enctype="multipart/form-data" action="{% url 'pythonix_admin:order_info' order_info.id %}">
                     {% csrf_token %}
                  <div class="box-body">
                      {% lite_include 'app_admin/__includes/form_fields/select.html' field=form.type_order %}
                      {% lite_include 'app_admin/__includes/form_fields/input_text.html' field=form.executor %}
                      {% lite_include 'app_admin/__includes/form_fields/input_text.html' field=form.client %}
                      {% lite_include 'app_admin/__includes/form_fields/input_text.html' field=form.address %}
                      {% lite_include 'app_admin/__includes/form_fields/radio.html' field=form.framed %}
                      {% lite_include 'app_admin/__includes/form_fields/input_text.html' field=form.description %}
                  </div><!-- /.box-body -->

                  <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Выполнить</button>
                  </div>
                </form>
              </div><!-- /.box -->



            </div><!--/.col (left) -->

          </div>   <!-- /.row -->
        </section><!-- /.content -->
{% endblock %}

{% block jscss_block_bottom %}
    {{ block.super }}
    <script type="application/javascript">

        // Выбор группы клиентов из списка
        $('#id_select_clients_group').change(function() {
            var client_group = $("select#id_select_clients_group").val();
            var page_url = '/pythonix_admin/get_free_ipaddress/' + client_group + '/';
            $.get(page_url, function(data) { //Выполняем запрос на получение списка свободных ip.

                    var text = "<option value=''>Выберите ip адрес</option>";
                    for (var i in data) {  //Наполняем список элементами.
                        add_element = "<option value="+i+">"+data[i]+"</option>";
                        text += add_element;

                    }
                    document.add_client_form.select_ip.innerHTML = text;
                });
        });

        // Выбор свободного ip адреса
        $('#select_ip').change(function() {
            var free_ip = $("select#select_ip").val();
            $('#id_ip_address').val(free_ip);
        });

        // Выбор физической сети
        $('#physical_networks').change(function() {
            var physical_network = $("select#physical_networks").val();
            if (physical_network != ""){

                // Список групп клиентов, выбранной сети
                var page_url = '/pythonix_admin/get_client_groups/' + physical_network + '/';
                $.get(page_url, function(data) {
                    var text = "<option value=''>Выберите группу клиентов</option>";
                    for (var i in data) {
                        add_element = "<option value="+i+">"+data[i]+"</option>";
                        text += add_element;

                    }
                    document.add_client_form.select_clients_group.innerHTML = text;
                });
            }

        });


        // Обновляем пароль
        $('#btn-update-password').click(function() {
            var page_url = '/pythonix_admin/update_password/' + {{ client_info.id }} + '/';
            $.get(page_url, function(data) {
                    if (data['error']){
                        $('#update-password-error').text(data['password']).show();
                    }
                    else {
                        $('#currentPassword').val(data['password']);
                    }

                });
            return false;
        });

        // Пополнение счета
        $('#btn-pay').click(function() {
            if ($("#id_temporary_pay").prop("checked")){
                var temporary_pay = 1;
            }
            else {
                var temporary_pay = 0;
            }
            var page_url = '/pythonix_admin/pay_balance/' + {{ client_info.id }} + '/' + $('#pay-sum').val() + '/' + temporary_pay + '/';
            $.get(page_url, function(data) {
                    $('#balance-pay-message').text(data['message']).show();
                    $('#id_balance').val(data['balance']);
                });
            return false;
        });

        // Включение отключение клиентв
        $('#btn-on-off-client-message').click(function() {
            var client_action = $("select#on-off-client").val();
            var page_url = '/pythonix_admin/client_on_off/' + {{ client_info.id }} + '/' + client_action + '/';
            $.get(page_url, function(data) {
                    $('#on-off-client-message').text(data['message']).show();
                });
            return false;
        });

        // Отправить данные монтажнику
        $('#btn-send-sms-info').click(function() {
            var employeer = $("select#employees").val();
            var page_url = '/pythonix_admin/send_sms_info_client_ajax/' + {{ client_info.id }} + '/' + employeer + '/';
            $.get(page_url, function(data) {
                    $('#send-sms-message').text(data['message']).show();
                });
            return false;
        });

        // Получение данных о подключении клиента
        $('#btn-client-status').click(function() {
            var page_url = '/pythonix_admin/get_status_client/' + {{ client_info.id }} + '/';
            $.get(page_url, function(data) {
                    $('#client-status-message').text(data['message']).show();
                    $('#client-arp').val(data['arp']);
                    $('#client-ppp').val(data['ppp']);
                });
            return false;
        });

    </script>
{% endblock %}